# Show all employees 
POST http://localhost:3000/routes/employee/user/showAllEmployees
Content-Type: application/json

###
# create new employee 
POST http://localhost:3000/routes/employee/admin/createNewEmployee
Content-Type: application/json

{
    "name":"Jamal Mostafa Eahsan",
    "position":"Software Engineer",
    "email":"Jamal@uxd.co.jp",
    "password":"12345678",
    "admin": true
}


###
# Update an Employee 
POST http://localhost:3000/routes/employee/admin/updateEmployee/62afee11d2ecaa8ae4473c4b
Content-Type: application/json

{ 
    "name":"Jamal Mostafa Eahsan"
}

###
#  Employee Login 
POST http://localhost:3000/routes/employee/user/userLogin
Content-Type: application/json

{
    "email": "jamal@uxd.co.jp",
    "password": "12345678"
}

###

POST http://localhost:3000/routes/employee/user/userLogout
Content-Type: application/json

###
#  Create Designation 
POST http://localhost:3000/routes/designation/admin/createNewDesignation
Content-Type: application/json

{
    "title": "Leader of Software Engineers",
    "rank": "11",
    "active_status": true
}



###
# Show all designations
POST http://localhost:3000/routes/designation/user/showAllDesignations
Content-Type: application/json
